{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fabricators_of_create.Porting-Lib",
    "module": "blocks",
    "version": "3.1.0-beta+1.20.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "blocks-3.1.0-beta+1.20.4.jar",
          "url": "blocks-3.1.0-beta+1.20.4.jar",
          "size": 187167,
          "sha512": "648836a65f3d73f9560b6aefc5be3cd313ee2aae70c33e61599abf65fde869db8d3872a8f3278fc0a30bb1917248d492e1a4a6a5821f6b10c0f55b036b1b0353",
          "sha256": "e2c2db5947fedf5959b9ec6d4298d266d0515d8e42f00c3a4e6f9afefad37f9f",
          "sha1": "cb2b45bf6696eda0afd0bd063870a2ce070eeece",
          "md5": "bff3e9ee78101f90bc7fdc0966c8bdc5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "blocks-3.1.0-beta+1.20.4.jar",
          "url": "blocks-3.1.0-beta+1.20.4.jar",
          "size": 187167,
          "sha512": "648836a65f3d73f9560b6aefc5be3cd313ee2aae70c33e61599abf65fde869db8d3872a8f3278fc0a30bb1917248d492e1a4a6a5821f6b10c0f55b036b1b0353",
          "sha256": "e2c2db5947fedf5959b9ec6d4298d266d0515d8e42f00c3a4e6f9afefad37f9f",
          "sha1": "cb2b45bf6696eda0afd0bd063870a2ce070eeece",
          "md5": "bff3e9ee78101f90bc7fdc0966c8bdc5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "blocks-3.1.0-beta+1.20.4-sources.jar",
          "url": "blocks-3.1.0-beta+1.20.4-sources.jar",
          "size": 4591,
          "sha512": "d08dc940aadf610898a7ddc900bdc2f5f95465acdb08844c2c4ebb59625280cb8927850320e343170c69310f8e6f4490ac80cb2bdfe9ad6df696e9f1bcdff2ff",
          "sha256": "b0461f265b14811d68054747b2f51720c97aecbe8cce8f9bf6933c3ce17ec346",
          "sha1": "540da79909c55056a41e3f61aa4cf01ecce6a092",
          "md5": "68385adbcd7e35fb02c93349f7260657"
        }
      ]
    }
  ]
}
