{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fabricators_of_create.Porting-Lib",
    "module": "common",
    "version": "3.1.0-beta+1.20.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "common-3.1.0-beta+1.20.4.jar",
          "url": "common-3.1.0-beta+1.20.4.jar",
          "size": 199853,
          "sha512": "3f39d0b6bed587e8ad81406ffd91b5564e1f1d57b503b155378abb8fe712be1d4ab9ee2021ee357c8db6207ed07fa300cc039c354945491b5f9557c5e1096ff2",
          "sha256": "553b1cfa1fd3d98f739addb7a29b52a3f998e030249accc4ebaeedc2b9bd9cf8",
          "sha1": "4b712353d888c956ea67b92e0cea8db1f2e48633",
          "md5": "2803216372124e8941aecbeae646a17c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "common-3.1.0-beta+1.20.4.jar",
          "url": "common-3.1.0-beta+1.20.4.jar",
          "size": 199853,
          "sha512": "3f39d0b6bed587e8ad81406ffd91b5564e1f1d57b503b155378abb8fe712be1d4ab9ee2021ee357c8db6207ed07fa300cc039c354945491b5f9557c5e1096ff2",
          "sha256": "553b1cfa1fd3d98f739addb7a29b52a3f998e030249accc4ebaeedc2b9bd9cf8",
          "sha1": "4b712353d888c956ea67b92e0cea8db1f2e48633",
          "md5": "2803216372124e8941aecbeae646a17c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "common-3.1.0-beta+1.20.4-sources.jar",
          "url": "common-3.1.0-beta+1.20.4-sources.jar",
          "size": 12610,
          "sha512": "14a74271f1a5a6d0307a4b55f89dfd49d0e49fe4bed1ec708f081b473763dc08b82c11049cbdf8173249f16a1290cd5cbd555a5ebad65f29b5653b828d3b4e52",
          "sha256": "6045f99f620788ba9c69b69db59a9df5be5617112d7076bc80362d4de36d380a",
          "sha1": "995344c0fe3d99186f05100b8934404bf46d8f77",
          "md5": "347dfe710314da14391956bba4f5f743"
        }
      ]
    }
  ]
}
