{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fabricators_of_create.Porting-Lib",
    "module": "entity",
    "version": "3.1.0-beta+1.20.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "mixin_extensions",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "entity-3.1.0-beta+1.20.4.jar",
          "url": "entity-3.1.0-beta+1.20.4.jar",
          "size": 458205,
          "sha512": "17b5862b34a85b42b9d953282f4a16e6adf5472e1121bff116afb50d78cff48f9304fb6b579151bc24d68d171c60aee403bd06a68ae9ffdcee1da185b1bba658",
          "sha256": "cca0963bdb83ce24aad3838fc6a7bf9f5342c5b1903255519e718783c2054a74",
          "sha1": "3bb1f22db60e3f7367c851a809f2968735f50ab7",
          "md5": "1dd839664fd8e178cac411c0fc8aca05"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "mixin_extensions",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "entity-3.1.0-beta+1.20.4.jar",
          "url": "entity-3.1.0-beta+1.20.4.jar",
          "size": 458205,
          "sha512": "17b5862b34a85b42b9d953282f4a16e6adf5472e1121bff116afb50d78cff48f9304fb6b579151bc24d68d171c60aee403bd06a68ae9ffdcee1da185b1bba658",
          "sha256": "cca0963bdb83ce24aad3838fc6a7bf9f5342c5b1903255519e718783c2054a74",
          "sha1": "3bb1f22db60e3f7367c851a809f2968735f50ab7",
          "md5": "1dd839664fd8e178cac411c0fc8aca05"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "entity-3.1.0-beta+1.20.4-sources.jar",
          "url": "entity-3.1.0-beta+1.20.4-sources.jar",
          "size": 103012,
          "sha512": "c22a6d6d10836119396d8a4e71a2bebf15ea6db46e242867adc626c6cca1e9969eba9685c914c88131ac1186bcb02641a90b7ef1a10209068030e529b1b66cd8",
          "sha256": "3ed7b5660be7838b275f5dffd7940d0f1eaade33c92a1dbc3e72c159123d2d2b",
          "sha1": "10dd15c937ce5444c1db40e5043836848979335e",
          "md5": "285691ed81d587407d126e751697340a"
        }
      ]
    }
  ]
}
