{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fabricators_of_create.Porting-Lib",
    "module": "registries",
    "version": "3.1.0-beta+1.20.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "registries-3.1.0-beta+1.20.4.jar",
          "url": "registries-3.1.0-beta+1.20.4.jar",
          "size": 194629,
          "sha512": "20e6639e9798bfba0d4dc347a2539e5809ebcc557a6980e51daffbb6fc39a36b90dd49b3628116b6caadf460bbee85f2d0af2ae4827144fec4ff0cea3e58d2e9",
          "sha256": "2a3681462d399b5c6ee9d33ef71555b3b49ac883f3c6a38116d511037c61dfd5",
          "sha1": "8407adf802f446ceae30a48f4beb2176e20266b6",
          "md5": "9379a71bb97e968575f4433232f90992"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "registries-3.1.0-beta+1.20.4.jar",
          "url": "registries-3.1.0-beta+1.20.4.jar",
          "size": 194629,
          "sha512": "20e6639e9798bfba0d4dc347a2539e5809ebcc557a6980e51daffbb6fc39a36b90dd49b3628116b6caadf460bbee85f2d0af2ae4827144fec4ff0cea3e58d2e9",
          "sha256": "2a3681462d399b5c6ee9d33ef71555b3b49ac883f3c6a38116d511037c61dfd5",
          "sha1": "8407adf802f446ceae30a48f4beb2176e20266b6",
          "md5": "9379a71bb97e968575f4433232f90992"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "registries-3.1.0-beta+1.20.4-sources.jar",
          "url": "registries-3.1.0-beta+1.20.4-sources.jar",
          "size": 7000,
          "sha512": "5bf13805b53cdb87ccb05d5f7472e3f53d857f1a8cc5deacda91d27e2a616f3045349abf680fb7c2119058a76f4f90e175c2c2bfb6c0587128b51197d2286baa",
          "sha256": "a7703ebc8fc34bd5ad1551de7bd859fef67551855ec8eb1c2a3741940d8bb838",
          "sha1": "28ab02d939cf2e5af970f61ba4458ee5052d79d6",
          "md5": "e9439fb9370b17d9de14f0d7311685e7"
        }
      ]
    }
  ]
}
