{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fabricators_of_create.Porting-Lib",
    "module": "lazy_registration",
    "version": "3.1.0-beta+1.20.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "lazy_registration-3.1.0-beta+1.20.4.jar",
          "url": "lazy_registration-3.1.0-beta+1.20.4.jar",
          "size": 191613,
          "sha512": "f5c58d0e523578759e92d7f1920db2a4b035c928f41261c26c9a791fbbb510d8a7a58a8ff67c0ebf7fb8261249cc1256ad62acc54e7fc68b7c35bb5067d85b20",
          "sha256": "f89abfa25fea33186f39f237df8411cd5513b67c93e05b0078e3249ba9bc3455",
          "sha1": "7b67485b17bd493f9dae4bde8d59c2e5d6ad16c6",
          "md5": "7371865ed246ea6ca1e167c6e21b5365"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "lazy_registration-3.1.0-beta+1.20.4.jar",
          "url": "lazy_registration-3.1.0-beta+1.20.4.jar",
          "size": 191613,
          "sha512": "f5c58d0e523578759e92d7f1920db2a4b035c928f41261c26c9a791fbbb510d8a7a58a8ff67c0ebf7fb8261249cc1256ad62acc54e7fc68b7c35bb5067d85b20",
          "sha256": "f89abfa25fea33186f39f237df8411cd5513b67c93e05b0078e3249ba9bc3455",
          "sha1": "7b67485b17bd493f9dae4bde8d59c2e5d6ad16c6",
          "md5": "7371865ed246ea6ca1e167c6e21b5365"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "lazy_registration-3.1.0-beta+1.20.4-sources.jar",
          "url": "lazy_registration-3.1.0-beta+1.20.4-sources.jar",
          "size": 5532,
          "sha512": "f60f7251d163edfc4bb1a9e5ac8e8aaf3a311d3b0f44b5aa9387af5f5e385819701cd52edd408353ba7678f60b4ae12a69499ff74bd1d44ce20a1e5494e5a47a",
          "sha256": "059ec924fb2f0da17a24abd86031781973d45a1aa4dba3d6cd8533f5bfb0b566",
          "sha1": "ae28da64ad56e4864c02eef6105bd7f562991c46",
          "md5": "52b574daf67b7d300e543a246bc2a767"
        }
      ]
    }
  ]
}
