{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fabricators_of_create.Porting-Lib",
    "module": "tags",
    "version": "3.1.0-beta+1.20.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "tags-3.1.0-beta+1.20.4.jar",
          "url": "tags-3.1.0-beta+1.20.4.jar",
          "size": 337241,
          "sha512": "5d6e8210513bff0b95feb12aee161fe8987f1d1ab3ca13713486fcdb767debb793441eff4c6838c6250a1f84c2790222c5f0853ecd35657a059ae483b434fa82",
          "sha256": "27bea02b89540057fb202c288e16dff08cdc636f8dca6ff1ad43e3da09416d66",
          "sha1": "09cd059146bda287aa016b45ecaae1736b94538c",
          "md5": "e248c886b406a1e7f6691261e6d7ae48"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "tags-3.1.0-beta+1.20.4.jar",
          "url": "tags-3.1.0-beta+1.20.4.jar",
          "size": 337241,
          "sha512": "5d6e8210513bff0b95feb12aee161fe8987f1d1ab3ca13713486fcdb767debb793441eff4c6838c6250a1f84c2790222c5f0853ecd35657a059ae483b434fa82",
          "sha256": "27bea02b89540057fb202c288e16dff08cdc636f8dca6ff1ad43e3da09416d66",
          "sha1": "09cd059146bda287aa016b45ecaae1736b94538c",
          "md5": "e248c886b406a1e7f6691261e6d7ae48"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "tags-3.1.0-beta+1.20.4-sources.jar",
          "url": "tags-3.1.0-beta+1.20.4-sources.jar",
          "size": 142561,
          "sha512": "d6e63798ab896f5c9dd606fd1450ccadc87c64cacc3ddfcc63b157bc914c89db8b567a39dfabf344c701119066668855995f06b42a02592b4e00ed3ad7d6d8ea",
          "sha256": "68ecae5ec6ca9dbdc32d034d898b59c31284eabc9b9f6070c56a21eec4d0c4e0",
          "sha1": "16b395b630f35d1d217c031b7fcd02e53f39ec99",
          "md5": "fb92349407e07bbb6c25042e765a75d3"
        }
      ]
    }
  ]
}
