{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fabricators_of_create.Porting-Lib",
    "module": "items",
    "version": "3.1.0-beta+1.20.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "items-3.1.0-beta+1.20.4.jar",
          "url": "items-3.1.0-beta+1.20.4.jar",
          "size": 205031,
          "sha512": "3e793c1902f803836146d975bf6717c7b916683689ecccbb1c7aafce7f455e6044442e6d1978f584c09470ef8f3dc266cfd985a869333b1b2a219acc2daf323d",
          "sha256": "863b2b1c2bb51d5129eb2d6946b7f0ee3bacf9cc76d1bac4e6f15fa6c206156e",
          "sha1": "7d0c3f537ccf58562d0d1f2875ee81715a78669e",
          "md5": "963a598546407d874937087c7f916995"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "items-3.1.0-beta+1.20.4.jar",
          "url": "items-3.1.0-beta+1.20.4.jar",
          "size": 205031,
          "sha512": "3e793c1902f803836146d975bf6717c7b916683689ecccbb1c7aafce7f455e6044442e6d1978f584c09470ef8f3dc266cfd985a869333b1b2a219acc2daf323d",
          "sha256": "863b2b1c2bb51d5129eb2d6946b7f0ee3bacf9cc76d1bac4e6f15fa6c206156e",
          "sha1": "7d0c3f537ccf58562d0d1f2875ee81715a78669e",
          "md5": "963a598546407d874937087c7f916995"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "items-3.1.0-beta+1.20.4-sources.jar",
          "url": "items-3.1.0-beta+1.20.4-sources.jar",
          "size": 15653,
          "sha512": "615f95f6b927d5307d97d1c534977de0ef18323a9c239294894274ac50cfb8a1cbdaec27ddb0a3f65c9fd68e11eae3c5807a45adf4b3bd43da7e9becc44157a5",
          "sha256": "8742c8a9c8e2df0fbef5fe37348cb84bcc246ad29e99dacc43d6c2ea99f98f35",
          "sha1": "cdc96fcae8d6961ea86e456c789eba550d7213cd",
          "md5": "8ac5dee681bb507f633d647911d76d08"
        }
      ]
    }
  ]
}
