{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fabricators_of_create.Porting-Lib",
    "module": "data",
    "version": "3.1.0-beta+1.20.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "utility",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "data-3.1.0-beta+1.20.4.jar",
          "url": "data-3.1.0-beta+1.20.4.jar",
          "size": 294460,
          "sha512": "5f7e4cfbdeebad1ea87a942ccf67780fe4f0f19f87cdf5f9f4210bffee5ebe4b18fe05b5237060ebccab32904ff6b387410bc95fdaa80a007e75eef987dd3099",
          "sha256": "51ced9c80c09942f1f043aedc5481f058a3eac75f5580d72024ade95a2c31e71",
          "sha1": "472d6d3fee36a65d7c2067b207256d177fd14d56",
          "md5": "e3a77d52e77ee72e57225b32a364c89f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "utility",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "data-3.1.0-beta+1.20.4.jar",
          "url": "data-3.1.0-beta+1.20.4.jar",
          "size": 294460,
          "sha512": "5f7e4cfbdeebad1ea87a942ccf67780fe4f0f19f87cdf5f9f4210bffee5ebe4b18fe05b5237060ebccab32904ff6b387410bc95fdaa80a007e75eef987dd3099",
          "sha256": "51ced9c80c09942f1f043aedc5481f058a3eac75f5580d72024ade95a2c31e71",
          "sha1": "472d6d3fee36a65d7c2067b207256d177fd14d56",
          "md5": "e3a77d52e77ee72e57225b32a364c89f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "data-3.1.0-beta+1.20.4-sources.jar",
          "url": "data-3.1.0-beta+1.20.4-sources.jar",
          "size": 30813,
          "sha512": "8f356cb5be5344dafd9bfe0ae947b137c1951114337221f278b955c86161d96d6f7d008d3c8797482df513d1ba50bf676c3a388115485358dc5000c7fb8d7fee",
          "sha256": "4c591fb50ba5b98e667be9f722df52cc5bfd81ec668b84eb37877fa67d69d508",
          "sha1": "b6404ea8e7311c0b81b3774eb5712f8c3483d4c3",
          "md5": "f473aa86bad6fe9ba87d8f6c168039f4"
        }
      ]
    }
  ]
}
