{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fabricators_of_create.Porting-Lib",
    "module": "chunk_loading",
    "version": "3.1.0-beta+1.20.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "chunk_loading-3.1.0-beta+1.20.4.jar",
          "url": "chunk_loading-3.1.0-beta+1.20.4.jar",
          "size": 212394,
          "sha512": "e77e76fbde584583aaf930d1d743c9004a1210912c902ffdcd1bb63d672b672097aced0554f9480deaaca8541d4df73d506e225801d8f4319037770bd381d642",
          "sha256": "fcc46d17b03f8fd633e9a2cce2b75999189580dcd94e3141d98e2d126f12d8cd",
          "sha1": "1d7d0f087a2c05a56657e9184165c4645a4f37a0",
          "md5": "78de7da33564a4fd5fd976e4f6d313b9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "chunk_loading-3.1.0-beta+1.20.4.jar",
          "url": "chunk_loading-3.1.0-beta+1.20.4.jar",
          "size": 212394,
          "sha512": "e77e76fbde584583aaf930d1d743c9004a1210912c902ffdcd1bb63d672b672097aced0554f9480deaaca8541d4df73d506e225801d8f4319037770bd381d642",
          "sha256": "fcc46d17b03f8fd633e9a2cce2b75999189580dcd94e3141d98e2d126f12d8cd",
          "sha1": "1d7d0f087a2c05a56657e9184165c4645a4f37a0",
          "md5": "78de7da33564a4fd5fd976e4f6d313b9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "chunk_loading-3.1.0-beta+1.20.4-sources.jar",
          "url": "chunk_loading-3.1.0-beta+1.20.4-sources.jar",
          "size": 16932,
          "sha512": "eee07848d666a7009d0a1ca429b68e947b6862725277a5d661593caa7b7549b6ac5b80d52e7a5f42a51590fbb4ac4433c37a114e74f4acc18d44b40f8de71c04",
          "sha256": "2a76676b29f15851f414a6f3430c3290606d18dc0b78a224d97c062580ab1a80",
          "sha1": "25486df0c997e721f1496a5766f48f5cd472b325",
          "md5": "bc457ecac48038f0f80269fc222e0325"
        }
      ]
    }
  ]
}
