{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fabricators_of_create.Porting-Lib",
    "module": "accessors",
    "version": "3.1.0-beta+1.20.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "accessors-3.1.0-beta+1.20.4.jar",
          "url": "accessors-3.1.0-beta+1.20.4.jar",
          "size": 238561,
          "sha512": "7449f4b055598383a5d82f872f6dc3e1490ad5a462cc64e7a19b99764c62d517d2d2c0e533b0ae0b7dbc8b78c457bf8e4753e68f60f3f55651156fdb93668172",
          "sha256": "776843d8341762f639f353a8e6ba8848cf2365c98f859fed21e9bbd87de2ecb8",
          "sha1": "0961019e2f672078fdf2a2f1dccc461df9e4d071",
          "md5": "fca833f1578dc08878f7a936559c689a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "accessors-3.1.0-beta+1.20.4.jar",
          "url": "accessors-3.1.0-beta+1.20.4.jar",
          "size": 238561,
          "sha512": "7449f4b055598383a5d82f872f6dc3e1490ad5a462cc64e7a19b99764c62d517d2d2c0e533b0ae0b7dbc8b78c457bf8e4753e68f60f3f55651156fdb93668172",
          "sha256": "776843d8341762f639f353a8e6ba8848cf2365c98f859fed21e9bbd87de2ecb8",
          "sha1": "0961019e2f672078fdf2a2f1dccc461df9e4d071",
          "md5": "fca833f1578dc08878f7a936559c689a"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "accessors-3.1.0-beta+1.20.4-sources.jar",
          "url": "accessors-3.1.0-beta+1.20.4-sources.jar",
          "size": 46906,
          "sha512": "34d7172211021f9089be7c34a1d3ea3a0345e5504592bb439a0b2a2c6b27b215b13a9678629c9d5cfe7cc7dd7efc75dac271a0f9e50d4670a797197211681e23",
          "sha256": "b6ffd6939063c0a811a6aaf86df32f00c4c8d75cdbfbbf9b8b589ad25dddd045",
          "sha1": "d50542b1258622cce553f86e5c17b054f9534263",
          "md5": "d62dc5b611fd291aa1696a461a480581"
        }
      ]
    }
  ]
}
