{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fabricators_of_create.Porting-Lib",
    "module": "level_events",
    "version": "3.1.0-beta+1.20.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "level_events-3.1.0-beta+1.20.4.jar",
          "url": "level_events-3.1.0-beta+1.20.4.jar",
          "size": 188898,
          "sha512": "873ed4ee71fc7d503468ac553faf4a28cc563472cdd6854f141698af14ddd97bef8d355e61ca96df64ec921694a3fd379b4c7b7cb4854d82a850963c7ef65548",
          "sha256": "5612828fec3c6d44de10b2b78baf8f88664000e022caeab758e1713b6fd9cf34",
          "sha1": "4ff65a648a5e990cedf0984527dd97d4d3948c6d",
          "md5": "9d6bb7524fc135af8a7f1807b4d2a4dc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "level_events-3.1.0-beta+1.20.4.jar",
          "url": "level_events-3.1.0-beta+1.20.4.jar",
          "size": 188898,
          "sha512": "873ed4ee71fc7d503468ac553faf4a28cc563472cdd6854f141698af14ddd97bef8d355e61ca96df64ec921694a3fd379b4c7b7cb4854d82a850963c7ef65548",
          "sha256": "5612828fec3c6d44de10b2b78baf8f88664000e022caeab758e1713b6fd9cf34",
          "sha1": "4ff65a648a5e990cedf0984527dd97d4d3948c6d",
          "md5": "9d6bb7524fc135af8a7f1807b4d2a4dc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "level_events-3.1.0-beta+1.20.4-sources.jar",
          "url": "level_events-3.1.0-beta+1.20.4-sources.jar",
          "size": 5337,
          "sha512": "bcc4a9992b9e89cfdac83b126440ebad82d8fe98e88c8dd6549905c3c95e361308363483d098dbf7569390dc766ce9b163f07032c6e31fcb637f51f6328f2c5a",
          "sha256": "759afdd2757d0957c1df2fc8cce1f97974347c0a5cb11140b85ef391fe5c30d0",
          "sha1": "6f28f39c178338f1696d3e6ff22a83506e8cefd6",
          "md5": "cae70a2285c59ca9d5ee7e2df72110f7"
        }
      ]
    }
  ]
}
