{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fabricators_of_create.Porting-Lib",
    "module": "asm",
    "version": "3.1.0-beta+1.20.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "asm-3.1.0-beta+1.20.4.jar",
          "url": "asm-3.1.0-beta+1.20.4.jar",
          "size": 258227,
          "sha512": "a372383442430bd78420868bfb7d29f1885d3291afdbacabb5a63b9ea64403a98beed664e0a55d0e6f8876d95b277838a0767ca1fec5087c90a84ff505f7968c",
          "sha256": "b23e65f5c80be579dc1d89e590a18d853752ebeb7a70454488235993072b9ac0",
          "sha1": "e511f3c132ad36326a6ae3120b7d3f32c3171fbb",
          "md5": "43717c36677421e520a29c833d270e01"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        },
        {
          "group": "com.github.Chocohead",
          "module": "Fabric-ASM",
          "version": {
            "requires": "v2.3"
          }
        }
      ],
      "files": [
        {
          "name": "asm-3.1.0-beta+1.20.4.jar",
          "url": "asm-3.1.0-beta+1.20.4.jar",
          "size": 258227,
          "sha512": "a372383442430bd78420868bfb7d29f1885d3291afdbacabb5a63b9ea64403a98beed664e0a55d0e6f8876d95b277838a0767ca1fec5087c90a84ff505f7968c",
          "sha256": "b23e65f5c80be579dc1d89e590a18d853752ebeb7a70454488235993072b9ac0",
          "sha1": "e511f3c132ad36326a6ae3120b7d3f32c3171fbb",
          "md5": "43717c36677421e520a29c833d270e01"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "asm-3.1.0-beta+1.20.4-sources.jar",
          "url": "asm-3.1.0-beta+1.20.4-sources.jar",
          "size": 5189,
          "sha512": "b09e47c4c106989c6e8c233afa35df2356c14b07006590f910803146175c56c085878be7689b6427afe62278a641afc920c027f7ebe8ddc22922f6d4fdf78166",
          "sha256": "268ec072d66e3ae4a1dfa205e6392a6ea9b577b86825bb47a10b42f3064658fb",
          "sha1": "8277a78b45fc585fc53686c5207018bae72acb4b",
          "md5": "92eda4d646b0889066209b125d58d5eb"
        }
      ]
    }
  ]
}
