{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fabricators_of_create.Porting-Lib",
    "module": "models",
    "version": "3.1.0-beta+1.20.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "model_loader",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "transfer",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "models-3.1.0-beta+1.20.4.jar",
          "url": "models-3.1.0-beta+1.20.4.jar",
          "size": 556275,
          "sha512": "f5ebe707dbe7e1ed57e80453c444f67cf3f5831c70d8db4066a1736ca4f17e1a529952e9c7442083808fbf7c3f005db494699aeb2fa39f8b8ab27c79fc426854",
          "sha256": "38f09a181fb7711957ac4cedf18ace0ffc6d9069d8d03a07cab2eb79dce7e55f",
          "sha1": "acc449743dd0b1a37384aaf4a6ffcaf7a4138079",
          "md5": "b377848a3e733fe8f5811027b7e45ca9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "model_loader",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "transfer",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "models-3.1.0-beta+1.20.4.jar",
          "url": "models-3.1.0-beta+1.20.4.jar",
          "size": 556275,
          "sha512": "f5ebe707dbe7e1ed57e80453c444f67cf3f5831c70d8db4066a1736ca4f17e1a529952e9c7442083808fbf7c3f005db494699aeb2fa39f8b8ab27c79fc426854",
          "sha256": "38f09a181fb7711957ac4cedf18ace0ffc6d9069d8d03a07cab2eb79dce7e55f",
          "sha1": "acc449743dd0b1a37384aaf4a6ffcaf7a4138079",
          "md5": "b377848a3e733fe8f5811027b7e45ca9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "models-3.1.0-beta+1.20.4-sources.jar",
          "url": "models-3.1.0-beta+1.20.4-sources.jar",
          "size": 48249,
          "sha512": "818698a0a21a7d455ababac8086f2e9a2365df4503f4e0cd718785bc3401cc7138d224d17c6f4d534f60bfb3babe12d4e08aaff0163e1cfdb59c2ff4a2087826",
          "sha256": "4a74e8aa6402591cd237989c764ed1964a523142588d4d722edd275acda73c4c",
          "sha1": "54f5da5a6213b287a28175a7a041c4d0870da777",
          "md5": "aa1da685594a744932e11ee19de15a02"
        }
      ]
    }
  ]
}
