{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fabricators_of_create.Porting-Lib",
    "module": "model_loader",
    "version": "3.1.0-beta+1.20.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "model_loader-3.1.0-beta+1.20.4.jar",
          "url": "model_loader-3.1.0-beta+1.20.4.jar",
          "size": 215065,
          "sha512": "5e5a79663358a48072ed7006ac0f7cf0b25da843b2e96ace9c5635d8d737e5a3832162f3096618611fd6e7c16709e5e6f0fa2cf7235fb50c7bd1224f8baa5e7f",
          "sha256": "3cf18d210ff5a79e5dbb65370493b309ce4eaf2e018c6a9b80cf6e4fb2147995",
          "sha1": "a739348a5fc0ce1c14ad638316268f7072cf72f9",
          "md5": "a979b3c421671fa7df3393e151631a3d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "model_loader-3.1.0-beta+1.20.4.jar",
          "url": "model_loader-3.1.0-beta+1.20.4.jar",
          "size": 215065,
          "sha512": "5e5a79663358a48072ed7006ac0f7cf0b25da843b2e96ace9c5635d8d737e5a3832162f3096618611fd6e7c16709e5e6f0fa2cf7235fb50c7bd1224f8baa5e7f",
          "sha256": "3cf18d210ff5a79e5dbb65370493b309ce4eaf2e018c6a9b80cf6e4fb2147995",
          "sha1": "a739348a5fc0ce1c14ad638316268f7072cf72f9",
          "md5": "a979b3c421671fa7df3393e151631a3d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "model_loader-3.1.0-beta+1.20.4-sources.jar",
          "url": "model_loader-3.1.0-beta+1.20.4-sources.jar",
          "size": 22450,
          "sha512": "5507dbf6607ed90cfae7298ea396b26174bfc50ce1b6761b5ed7132d596b4a2aed362e2929924aa9e82e0b99d73defde325b0fa1d492a5b6e1c37fdd28041e8c",
          "sha256": "e718e807e0a665309cf76bc5033d0fec187d30e92e022a966c169f528c2148cf",
          "sha1": "d489d47a503afd533fd1b513356b2aefcb34f6ba",
          "md5": "d423d9d431d70a467cb22333da4ae521"
        }
      ]
    }
  ]
}
