{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fabricators_of_create.Porting-Lib",
    "module": "obj_loader",
    "version": "3.1.0-beta+1.20.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "model_loader",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "obj_loader-3.1.0-beta+1.20.4.jar",
          "url": "obj_loader-3.1.0-beta+1.20.4.jar",
          "size": 292029,
          "sha512": "b13e7e4d78ad274a5410eca9ed6835004ddfc39c148a1986e2a3f642fb79ef08dbde47c6eb9039ae3d2f4ef2c6db0e51546ccd02b265f0c20b314f2060bcf54d",
          "sha256": "ee141e8468699c60864b5f436a12ac995d2f4464e6c4917f10760aa0ca871b6a",
          "sha1": "50451949b65190a6261e8909e217e44ad4557a79",
          "md5": "08d83cf0b7d7181955d0e7c8a3de4e02"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "model_loader",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "obj_loader-3.1.0-beta+1.20.4.jar",
          "url": "obj_loader-3.1.0-beta+1.20.4.jar",
          "size": 292029,
          "sha512": "b13e7e4d78ad274a5410eca9ed6835004ddfc39c148a1986e2a3f642fb79ef08dbde47c6eb9039ae3d2f4ef2c6db0e51546ccd02b265f0c20b314f2060bcf54d",
          "sha256": "ee141e8468699c60864b5f436a12ac995d2f4464e6c4917f10760aa0ca871b6a",
          "sha1": "50451949b65190a6261e8909e217e44ad4557a79",
          "md5": "08d83cf0b7d7181955d0e7c8a3de4e02"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "obj_loader-3.1.0-beta+1.20.4-sources.jar",
          "url": "obj_loader-3.1.0-beta+1.20.4-sources.jar",
          "size": 15294,
          "sha512": "dc0390e87b7afea10f98019acdd10d7c7dd9dab575f6845fa775e6df1a45b0dd795900ed8dc4c40355c1623ef30f95e1f247eb0d5d9fb7eb22b8d5a15ab85fb9",
          "sha256": "50e6f8ec9cc1e9da604903efa681775fb04dc099c58084cb7b4e01363fb238b4",
          "sha1": "fb2b9b415e671b2d2ad97989929b434eefbba2f6",
          "md5": "e37cb70c3a664957094c270bef72e8a9"
        }
      ]
    }
  ]
}
