{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fabricators_of_create.Porting-Lib",
    "module": "config",
    "version": "3.1.0-beta+1.20.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.6"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.6.6"
          }
        }
      ],
      "files": [
        {
          "name": "config-3.1.0-beta+1.20.4.jar",
          "url": "config-3.1.0-beta+1.20.4.jar",
          "size": 452778,
          "sha512": "2c9a6bedac7e1b295bc67e85c6719af9594d3f62085b38917fb9cd09bc001dd860fb4a71b57ed59bbea609e36a14ab3d8d2f8bdb9876b0757768c8b903fed01a",
          "sha256": "7e8f301619cd6d403687013ad88a7bdc5e89534c72e371a8bb6b449d73399401",
          "sha1": "d5dd942806bbbfe0cba601a656f6be317d51957c",
          "md5": "120a45d09e1db2179690cc2c2abf464e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "toml",
          "version": {
            "requires": "3.6.6"
          }
        },
        {
          "group": "com.electronwill.night-config",
          "module": "core",
          "version": {
            "requires": "3.6.6"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "config-3.1.0-beta+1.20.4.jar",
          "url": "config-3.1.0-beta+1.20.4.jar",
          "size": 452778,
          "sha512": "2c9a6bedac7e1b295bc67e85c6719af9594d3f62085b38917fb9cd09bc001dd860fb4a71b57ed59bbea609e36a14ab3d8d2f8bdb9876b0757768c8b903fed01a",
          "sha256": "7e8f301619cd6d403687013ad88a7bdc5e89534c72e371a8bb6b449d73399401",
          "sha1": "d5dd942806bbbfe0cba601a656f6be317d51957c",
          "md5": "120a45d09e1db2179690cc2c2abf464e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "config-3.1.0-beta+1.20.4-sources.jar",
          "url": "config-3.1.0-beta+1.20.4-sources.jar",
          "size": 21328,
          "sha512": "5439d8af75e68e3b41a5ca12ff900fc48ce1f0ba169a8ddfd4a825950c31d78f9f12bf19bf976a7d8ef5b8e22e53a503a1ca189c48fff81c446b9eaf7ddd11bf",
          "sha256": "d4c586c047b06eaedc931debee6d9bee1c4ae714f45f45f90399f9580ba8bd16",
          "sha1": "d1f29db901960f872c922417f14d516ca5894b05",
          "md5": "518d9b0a8998d3fb885228001ef22322"
        }
      ]
    }
  ]
}
