{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fabricators_of_create.Porting-Lib",
    "module": "model_builders",
    "version": "3.1.0-beta+1.20.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "model_generators",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "model_loader",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "model_builders-3.1.0-beta+1.20.4.jar",
          "url": "model_builders-3.1.0-beta+1.20.4.jar",
          "size": 587286,
          "sha512": "e396af6acfe30c11474f7b5a3123b78aa28109e5ec2e71792823b9cd93053e193881a9a590405f634172f0ccc03cdc2f5547b2ad453174d1f723372b0f5e6b6f",
          "sha256": "f1bd15a9f7cc9da4f0367aa66b570495cb1ed009e51cfe383784a414f69bd402",
          "sha1": "7c3347cd44b0ae591b49a8f5db981b6277858380",
          "md5": "6f919c20c6b106ac64c48ddf9f565070"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "model_generators",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "model_loader",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "model_builders-3.1.0-beta+1.20.4.jar",
          "url": "model_builders-3.1.0-beta+1.20.4.jar",
          "size": 587286,
          "sha512": "e396af6acfe30c11474f7b5a3123b78aa28109e5ec2e71792823b9cd93053e193881a9a590405f634172f0ccc03cdc2f5547b2ad453174d1f723372b0f5e6b6f",
          "sha256": "f1bd15a9f7cc9da4f0367aa66b570495cb1ed009e51cfe383784a414f69bd402",
          "sha1": "7c3347cd44b0ae591b49a8f5db981b6277858380",
          "md5": "6f919c20c6b106ac64c48ddf9f565070"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "model_builders-3.1.0-beta+1.20.4-sources.jar",
          "url": "model_builders-3.1.0-beta+1.20.4-sources.jar",
          "size": 5106,
          "sha512": "8647e2fd98fc91c0354c8c0c91fbab6dfcd351571f486286b17a206f0a20976b07e9a5bad57ad170c004d3d08e5c18e8ad8137cca5b5bf76e9ddc37f034e62a2",
          "sha256": "7f57571d1aac7e3006fd458557facc59a41f1058a8478046886cdb18a9523722",
          "sha1": "90c415d0c53b8506c8827bf20ab7422ff8d8a474",
          "md5": "bc9fdf49641f85c28c0840f7f886870e"
        }
      ]
    }
  ]
}
