{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fabricators_of_create.Porting-Lib",
    "module": "attributes",
    "version": "3.1.0-beta+1.20.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "asm",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        },
        {
          "group": "com.jamieswhiteshirt",
          "module": "reach-entity-attributes",
          "version": {
            "requires": "2.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "attributes-3.1.0-beta+1.20.4.jar",
          "url": "attributes-3.1.0-beta+1.20.4.jar",
          "size": 330632,
          "sha512": "5070ddfaf4210cb1cb221d593abd11163046e87867426439a723a1bb663ec5da6a33f3c00c44dd3fe076ab9f828913a044f3a664e16d9a166f9280173fa55961",
          "sha256": "91581d3139186111bb94768474d8df3e0af6003249c349b47fb135684d9edd30",
          "sha1": "e657357c129d8a406182f14856de41cd471c0a55",
          "md5": "e587b96e7be943c73c86e892fc154d86"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "asm",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        },
        {
          "group": "com.jamieswhiteshirt",
          "module": "reach-entity-attributes",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "attributes-3.1.0-beta+1.20.4.jar",
          "url": "attributes-3.1.0-beta+1.20.4.jar",
          "size": 330632,
          "sha512": "5070ddfaf4210cb1cb221d593abd11163046e87867426439a723a1bb663ec5da6a33f3c00c44dd3fe076ab9f828913a044f3a664e16d9a166f9280173fa55961",
          "sha256": "91581d3139186111bb94768474d8df3e0af6003249c349b47fb135684d9edd30",
          "sha1": "e657357c129d8a406182f14856de41cd471c0a55",
          "md5": "e587b96e7be943c73c86e892fc154d86"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "attributes-3.1.0-beta+1.20.4-sources.jar",
          "url": "attributes-3.1.0-beta+1.20.4-sources.jar",
          "size": 9651,
          "sha512": "ccad7b7e13a52e060ccadada074080a6351c09c34785264f11a635b9903cbbde4d8ab317838d9d44aee36ab12a6b1a9d34d2cad00da0af89643a6bff2cde4778",
          "sha256": "d54abd92076ef4fd9f7235947f34053fb24ed58332a661da943905340d2c95d9",
          "sha1": "feb0fa3febdcbbab26edcd7c115b79a601346652",
          "md5": "cf7b1b226c15a1ad87242357e88c6ea7"
        }
      ]
    }
  ]
}
