{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fabricators_of_create.Porting-Lib",
    "module": "brewing",
    "version": "3.1.0-beta+1.20.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "brewing-3.1.0-beta+1.20.4.jar",
          "url": "brewing-3.1.0-beta+1.20.4.jar",
          "size": 194357,
          "sha512": "51413972536c5381bdbdbcb3d058e896727d6f4837f12f81533cf03713102ab1d46d665a1dab1cb29276ef12751f5ffbad66f926b970b0d6e883a869f5ee4304",
          "sha256": "4a0fd07acd25e8a1a86fbdff09e647d08edafcb1db14a09036f5dd6eff508cfe",
          "sha1": "87a43a8318bf0fee64a0b2125ebc20c605423862",
          "md5": "1f3df5c07cf29d7748ba6c16bd7fda2d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "brewing-3.1.0-beta+1.20.4.jar",
          "url": "brewing-3.1.0-beta+1.20.4.jar",
          "size": 194357,
          "sha512": "51413972536c5381bdbdbcb3d058e896727d6f4837f12f81533cf03713102ab1d46d665a1dab1cb29276ef12751f5ffbad66f926b970b0d6e883a869f5ee4304",
          "sha256": "4a0fd07acd25e8a1a86fbdff09e647d08edafcb1db14a09036f5dd6eff508cfe",
          "sha1": "87a43a8318bf0fee64a0b2125ebc20c605423862",
          "md5": "1f3df5c07cf29d7748ba6c16bd7fda2d"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "brewing-3.1.0-beta+1.20.4-sources.jar",
          "url": "brewing-3.1.0-beta+1.20.4-sources.jar",
          "size": 9645,
          "sha512": "f93c6df78b1489b17bfef84096c56b192a45207a58ff9cfd9b58d3c80ddd6079ade095a57545d2c206e37f60658122bac4095eff06f04a7fe9a818173b35d774",
          "sha256": "544d0a4d2a1801d995a07f612ca96f756e8035f8b58f4c9aea1fac79d9b90ea1",
          "sha1": "d6a17fad2995e56827d11295d5bb5b80adc7fffb",
          "md5": "ce36dabba8452e08b2ed606db961f784"
        }
      ]
    }
  ]
}
