{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fabricators_of_create.Porting-Lib",
    "module": "gui_utils",
    "version": "3.1.0-beta+1.20.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "gui_utils-3.1.0-beta+1.20.4.jar",
          "url": "gui_utils-3.1.0-beta+1.20.4.jar",
          "size": 195318,
          "sha512": "294683a2efbad3789b01c8fcee087abeaf6516937a3a3ed4cea750e44ca1bd1fe30f7b796780ac44f45ec91e1b71c52964906e3779ab5df82b2a4521c91743a5",
          "sha256": "a19c65bfe7c9400978ba4692cca13cba14957a488df3839b650a6ff60bfe5aa6",
          "sha1": "c0de7a71190609b03f4bdbdced35be3f5328c238",
          "md5": "479d1f3c580d7bbaa227a50aaa8b2e0b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "gui_utils-3.1.0-beta+1.20.4.jar",
          "url": "gui_utils-3.1.0-beta+1.20.4.jar",
          "size": 195318,
          "sha512": "294683a2efbad3789b01c8fcee087abeaf6516937a3a3ed4cea750e44ca1bd1fe30f7b796780ac44f45ec91e1b71c52964906e3779ab5df82b2a4521c91743a5",
          "sha256": "a19c65bfe7c9400978ba4692cca13cba14957a488df3839b650a6ff60bfe5aa6",
          "sha1": "c0de7a71190609b03f4bdbdced35be3f5328c238",
          "md5": "479d1f3c580d7bbaa227a50aaa8b2e0b"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gui_utils-3.1.0-beta+1.20.4-sources.jar",
          "url": "gui_utils-3.1.0-beta+1.20.4-sources.jar",
          "size": 8935,
          "sha512": "c1b6389982ea48a9d42774159738cc5545275ade7458617bf6f9697b58f182750c45661f7e9d460b7d6c98fff2ba97e06250171c3f0ac042a4bfd49ad469cc6b",
          "sha256": "013876aa6744de5cd39144850cbcf89d7720de7b37280f563646bedeff5169d7",
          "sha1": "044f08b666804c393b279ab11725ed4dc4f58a3d",
          "md5": "7b91113a62774d1f9f80721fa6b4541d"
        }
      ]
    }
  ]
}
