{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fabricators_of_create.Porting-Lib",
    "module": "mixin_extensions",
    "version": "3.1.0-beta+1.20.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "mixin_extensions-3.1.0-beta+1.20.4.jar",
          "url": "mixin_extensions-3.1.0-beta+1.20.4.jar",
          "size": 195733,
          "sha512": "2c80af5688ee2a23d742033fecd4d79d71e59b574a3ba5f019de92a12801090e360f605f05e793f885803c557274beb711fa2444390a91387440e368fcc3258d",
          "sha256": "ecc3d4d62650bdb943e330d41d7a5dd88f11bfdb9fbdcd826ec1a3cabe478d82",
          "sha1": "71edba7f3d41ea9813c8e9ff7c11530a44ecf9b4",
          "md5": "27ef0daa6d0e3755ba9a40bedf3e83e5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "mixin_extensions-3.1.0-beta+1.20.4.jar",
          "url": "mixin_extensions-3.1.0-beta+1.20.4.jar",
          "size": 195733,
          "sha512": "2c80af5688ee2a23d742033fecd4d79d71e59b574a3ba5f019de92a12801090e360f605f05e793f885803c557274beb711fa2444390a91387440e368fcc3258d",
          "sha256": "ecc3d4d62650bdb943e330d41d7a5dd88f11bfdb9fbdcd826ec1a3cabe478d82",
          "sha1": "71edba7f3d41ea9813c8e9ff7c11530a44ecf9b4",
          "md5": "27ef0daa6d0e3755ba9a40bedf3e83e5"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mixin_extensions-3.1.0-beta+1.20.4-sources.jar",
          "url": "mixin_extensions-3.1.0-beta+1.20.4-sources.jar",
          "size": 11000,
          "sha512": "ee4a92a80ebf35a4f971cea439c38cbb9de8d0e05dbb3dc7fc0839563df25350c30ed7b7738737b11a514af09c5c11ebe75d3aa7bfa0e9ad4e1dd7b7d480a531",
          "sha256": "26a344bea90f6f3c773cfea2e25568953e6915aa0f6169435411fa8f230a06b2",
          "sha1": "7f52c25b219cd3202697d06d4b664e7d864d2281",
          "md5": "bcbbde0e1d1f8e4bc48e6ca6344413ba"
        }
      ]
    }
  ]
}
