{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fabricators_of_create.Porting-Lib",
    "module": "model_generators",
    "version": "3.1.0-beta+1.20.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "model_materials",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "data",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "model_generators-3.1.0-beta+1.20.4.jar",
          "url": "model_generators-3.1.0-beta+1.20.4.jar",
          "size": 473597,
          "sha512": "fa6c4712e5847f0f4484f6662a61dd1604447f60ef4f10378db18649787e14f5c96c42523d422a730dd23353078a8cd2d3d54646cad01436104383e9139a8944",
          "sha256": "1478bc684a7219b2a4ff8d1febe2c9aca6b70364d021cbd347d6f61fce728cfe",
          "sha1": "d46ac98ae6d2a0dc2d8f04d96673d198caf6ab77",
          "md5": "ccb83a130b0c6a3e29a3f43b21d19d70"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "model_materials",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "data",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "model_generators-3.1.0-beta+1.20.4.jar",
          "url": "model_generators-3.1.0-beta+1.20.4.jar",
          "size": 473597,
          "sha512": "fa6c4712e5847f0f4484f6662a61dd1604447f60ef4f10378db18649787e14f5c96c42523d422a730dd23353078a8cd2d3d54646cad01436104383e9139a8944",
          "sha256": "1478bc684a7219b2a4ff8d1febe2c9aca6b70364d021cbd347d6f61fce728cfe",
          "sha1": "d46ac98ae6d2a0dc2d8f04d96673d198caf6ab77",
          "md5": "ccb83a130b0c6a3e29a3f43b21d19d70"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "model_generators-3.1.0-beta+1.20.4-sources.jar",
          "url": "model_generators-3.1.0-beta+1.20.4-sources.jar",
          "size": 38343,
          "sha512": "53614b00859ff616c0ecc1e076209cd4f2e9a82314c9410d89a4dd49ddfdb329787fd7f95a26a9ca0cae1e1fa3a20a03c7172a75435b4b56d5839a742bddf610",
          "sha256": "aa417aeca8e3ff66f7ef0269472b73695aedef5a25866576c89d94ae995d0a7f",
          "sha1": "757baee8cd9eebd70a58d8441f7879a01634c07b",
          "md5": "67a83ee63fb209cf853309810b87df11"
        }
      ]
    }
  ]
}
