{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fabricators_of_create.Porting-Lib",
    "module": "utility",
    "version": "3.1.0-beta+1.20.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "utility-3.1.0-beta+1.20.4.jar",
          "url": "utility-3.1.0-beta+1.20.4.jar",
          "size": 192992,
          "sha512": "c33a1707537142d4a7adf1479f482f4e87b1b5514bc0d6ae7b97ed3c18d4b7794c1079014b5c8663d6f32e817e8b9289f62cbe006d96490fc5af6ee729df5ba1",
          "sha256": "650bee4f5c33a0fce3ca30c274607562bd35d3b75bb0317aab39678e7ae6fa87",
          "sha1": "5e5326306e4b306dedd0f5be6fdf3e980493d339",
          "md5": "523d93efdaa75aab8b5f0984a668e036"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "utility-3.1.0-beta+1.20.4.jar",
          "url": "utility-3.1.0-beta+1.20.4.jar",
          "size": 192992,
          "sha512": "c33a1707537142d4a7adf1479f482f4e87b1b5514bc0d6ae7b97ed3c18d4b7794c1079014b5c8663d6f32e817e8b9289f62cbe006d96490fc5af6ee729df5ba1",
          "sha256": "650bee4f5c33a0fce3ca30c274607562bd35d3b75bb0317aab39678e7ae6fa87",
          "sha1": "5e5326306e4b306dedd0f5be6fdf3e980493d339",
          "md5": "523d93efdaa75aab8b5f0984a668e036"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "utility-3.1.0-beta+1.20.4-sources.jar",
          "url": "utility-3.1.0-beta+1.20.4-sources.jar",
          "size": 7164,
          "sha512": "ab00c256c5511383523df0be668800ad51e7158b00bf24f5ff0079b2081bbe945380bfc63de94a9b28d88d1ba994a5bc69f3720a39c3d40aeadfefb0aab737d4",
          "sha256": "b8a1b5e77dede57fbc6eba7609dde918e6a6d6080f1958d2eb6152786f1b8d37",
          "sha1": "1825153e7b65eec2d52fc891beabe744aeafee5d",
          "md5": "228933a3638b92c38680a60a83862f97"
        }
      ]
    }
  ]
}
