{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fabricators_of_create.Porting-Lib",
    "module": "networking",
    "version": "3.1.0-beta+1.20.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "networking-3.1.0-beta+1.20.4.jar",
          "url": "networking-3.1.0-beta+1.20.4.jar",
          "size": 193316,
          "sha512": "5e6bd75b98d5a676d02cd7938c31ff4977547501ffc640e21102bb76c6631e96499a216eacbf178ce3c386839ee5f628f1621be8407779fce46112c03afc1226",
          "sha256": "ff18a8b0734c1713e87c75ec71eb24ded902af3385b7ed79e3c66e14f0b8aa8b",
          "sha1": "8c17c33c135eee0cfd87ee9926bc92a332dbf656",
          "md5": "5811edb9fa484c075ecdfc39473db365"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "networking-3.1.0-beta+1.20.4.jar",
          "url": "networking-3.1.0-beta+1.20.4.jar",
          "size": 193316,
          "sha512": "5e6bd75b98d5a676d02cd7938c31ff4977547501ffc640e21102bb76c6631e96499a216eacbf178ce3c386839ee5f628f1621be8407779fce46112c03afc1226",
          "sha256": "ff18a8b0734c1713e87c75ec71eb24ded902af3385b7ed79e3c66e14f0b8aa8b",
          "sha1": "8c17c33c135eee0cfd87ee9926bc92a332dbf656",
          "md5": "5811edb9fa484c075ecdfc39473db365"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "networking-3.1.0-beta+1.20.4-sources.jar",
          "url": "networking-3.1.0-beta+1.20.4-sources.jar",
          "size": 5805,
          "sha512": "a9f994072a89c9b2ffcce8b3cc6c35e15e700d07bdfdf93fca12ca273268f1deee7a479ab83bfa2772f165bd3995caee2ff5352b05547632ba92f741f9ac92fe",
          "sha256": "5522970d1fc31be872a1bb88f71474a12509f98cfada2b8854c385ed5ea9f706",
          "sha1": "56c702dbdc7d23d4300b381c25cf7772690e33e4",
          "md5": "e9a7b9d0aae32de62ea2deb1570b2001"
        }
      ]
    }
  ]
}
