{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fabricators_of_create.Porting-Lib",
    "module": "core",
    "version": "3.1.0-beta+1.20.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "gametest",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "core-3.1.0-beta+1.20.4.jar",
          "url": "core-3.1.0-beta+1.20.4.jar",
          "size": 140482,
          "sha512": "1679f246658b780257c4570b0c5c39d187080d02a81dfedc5e982b151eefc8d27a8f5eb31d40a5549c7a43acdc2c75f8d0875e45d0f1ee9895a69b1bd49c47c6",
          "sha256": "ed7d20497a05bf465ce75e1e7f5e1620d3fc40e5de37c6c5649377bf482001ec",
          "sha1": "8a6ca8285b4de784a36850375dc35162521a8e4d",
          "md5": "3da7f7c9f943b5e58c7595c70887b96c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "gametest",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "core-3.1.0-beta+1.20.4.jar",
          "url": "core-3.1.0-beta+1.20.4.jar",
          "size": 140482,
          "sha512": "1679f246658b780257c4570b0c5c39d187080d02a81dfedc5e982b151eefc8d27a8f5eb31d40a5549c7a43acdc2c75f8d0875e45d0f1ee9895a69b1bd49c47c6",
          "sha256": "ed7d20497a05bf465ce75e1e7f5e1620d3fc40e5de37c6c5649377bf482001ec",
          "sha1": "8a6ca8285b4de784a36850375dc35162521a8e4d",
          "md5": "3da7f7c9f943b5e58c7595c70887b96c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "core-3.1.0-beta+1.20.4-sources.jar",
          "url": "core-3.1.0-beta+1.20.4-sources.jar",
          "size": 5612,
          "sha512": "51d3a3fa6bbb82039a6f2830aed9f1b97f0941e149f72e25ba1eeeb8b0cf12089b013f21052fa19157c14ee97c779a0e40618c1d001911e8b6a47a6ef344e536",
          "sha256": "12ea34ff4b9b87004c174707c74de76c1d745e9c808e211a9dff4f896ed7a258",
          "sha1": "369117175ce7a4d2dbb0c6f352617b94d24187ac",
          "md5": "2beaae4540de9d33f443b57bf078d3f4"
        }
      ]
    }
  ]
}
