{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fabricators_of_create.Porting-Lib",
    "module": "transfer",
    "version": "3.1.0-beta+1.20.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "fluids",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "transfer-3.1.0-beta+1.20.4.jar",
          "url": "transfer-3.1.0-beta+1.20.4.jar",
          "size": 359245,
          "sha512": "209e08d6c0a5b46d2e4f60846903e45c49e207ec8d4949610618116e7accb22be48b140adf25f43593f35a20916ae5ff0b7eb29bda92fe0f75a536c5c6b553dc",
          "sha256": "f26cb218be9d39d60d33587774c07420150d2b7b516bb04d1fe332c32a0579f8",
          "sha1": "389b4f80a1a5231ef7f3768360fe74a09ddeba75",
          "md5": "f215e7516edf78d7cec5d4bd06ce21b9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "fluids",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "transfer-3.1.0-beta+1.20.4.jar",
          "url": "transfer-3.1.0-beta+1.20.4.jar",
          "size": 359245,
          "sha512": "209e08d6c0a5b46d2e4f60846903e45c49e207ec8d4949610618116e7accb22be48b140adf25f43593f35a20916ae5ff0b7eb29bda92fe0f75a536c5c6b553dc",
          "sha256": "f26cb218be9d39d60d33587774c07420150d2b7b516bb04d1fe332c32a0579f8",
          "sha1": "389b4f80a1a5231ef7f3768360fe74a09ddeba75",
          "md5": "f215e7516edf78d7cec5d4bd06ce21b9"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "transfer-3.1.0-beta+1.20.4-sources.jar",
          "url": "transfer-3.1.0-beta+1.20.4-sources.jar",
          "size": 54427,
          "sha512": "5e9582b789059f00d46889145b36b82c267c5f56385b62b12ef802ed9eebf119d389aa63fcb79d82834f791689b1efbaabe4792f65ad9a5b767d5dd716a644ac",
          "sha256": "ce9150291a68e95601f9cbb682ef2b28048f145d234af10ae13d9bdbbb8fd802",
          "sha1": "266805e0f77039b32f7fc163e91be8f7bbdfcab2",
          "md5": "b1b7c495e6881f1b3706b5a0d80922d0"
        }
      ]
    }
  ]
}
