{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fabricators_of_create.Porting-Lib",
    "module": "client_events",
    "version": "3.1.0-beta+1.20.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "client_events-3.1.0-beta+1.20.4.jar",
          "url": "client_events-3.1.0-beta+1.20.4.jar",
          "size": 271759,
          "sha512": "83e83e5e7c49f519deb893c2f9b0faa841845f310ddbaf80a111f722e559730892bb926b87599b258f64105fe8a6999e3fffb0c3ae65b196fe43e88907bd8226",
          "sha256": "7217fb673ff0dc4ff18bf0d83bb6aae3507659fcc256ecc51b3d22a9fdfe5587",
          "sha1": "4e0e387d67cf34697f764b00d2653b7aaa1968e3",
          "md5": "6b32e07524965b4432c910d7c6caa97f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        },
        {
          "group": "com.github.Chocohead",
          "module": "Fabric-ASM",
          "version": {
            "requires": "v2.3"
          }
        }
      ],
      "files": [
        {
          "name": "client_events-3.1.0-beta+1.20.4.jar",
          "url": "client_events-3.1.0-beta+1.20.4.jar",
          "size": 271759,
          "sha512": "83e83e5e7c49f519deb893c2f9b0faa841845f310ddbaf80a111f722e559730892bb926b87599b258f64105fe8a6999e3fffb0c3ae65b196fe43e88907bd8226",
          "sha256": "7217fb673ff0dc4ff18bf0d83bb6aae3507659fcc256ecc51b3d22a9fdfe5587",
          "sha1": "4e0e387d67cf34697f764b00d2653b7aaa1968e3",
          "md5": "6b32e07524965b4432c910d7c6caa97f"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "client_events-3.1.0-beta+1.20.4-sources.jar",
          "url": "client_events-3.1.0-beta+1.20.4-sources.jar",
          "size": 15265,
          "sha512": "cd243948e9a04b393dbb7fc4e017573f6e9056a850067d8134df9924987debc3fded32bc5ca20ffa0a043266e13785ddbef0174440f040f2bdcfba3ec44e4f08",
          "sha256": "663bb364485f616c31771fac89bf8ea581a3e1685660a6ef474932aa350086ba",
          "sha1": "08276cee3bdf181140e02dd8ccca5f8c28e4e217",
          "md5": "3efa353bd0e10ca4f87414762f7c5403"
        }
      ]
    }
  ]
}
