{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fabricators_of_create.Porting-Lib",
    "module": "loot",
    "version": "3.1.0-beta+1.20.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "lazy_registration",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "loot-3.1.0-beta+1.20.4.jar",
          "url": "loot-3.1.0-beta+1.20.4.jar",
          "size": 270373,
          "sha512": "d6c2241de604fdea67dbd7d4637747a8369c4ea412f89eb26001dfdd6f792eb6758b4d95d6c3781f47669e13e938cdded699e00b4bba9ed60341dc521aa6778e",
          "sha256": "5219c5d1c874b3daceb9e515148a469b6ff848811ab33190d8aaabd721312b79",
          "sha1": "d158e5b485808988e23f22fae1bbb33aa64753b0",
          "md5": "12a6198c39fd4645bb301fc3c5861df8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "lazy_registration",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "loot-3.1.0-beta+1.20.4.jar",
          "url": "loot-3.1.0-beta+1.20.4.jar",
          "size": 270373,
          "sha512": "d6c2241de604fdea67dbd7d4637747a8369c4ea412f89eb26001dfdd6f792eb6758b4d95d6c3781f47669e13e938cdded699e00b4bba9ed60341dc521aa6778e",
          "sha256": "5219c5d1c874b3daceb9e515148a469b6ff848811ab33190d8aaabd721312b79",
          "sha1": "d158e5b485808988e23f22fae1bbb33aa64753b0",
          "md5": "12a6198c39fd4645bb301fc3c5861df8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "loot-3.1.0-beta+1.20.4-sources.jar",
          "url": "loot-3.1.0-beta+1.20.4-sources.jar",
          "size": 21391,
          "sha512": "39614e876ad063a07f1718105c0f9d0d6192ee26fffea13f7bfedf9c61b8bf0ff9286c489399ac389f71b1b515b34ba06ff953161aad0dc00471ebff2a01d8ba",
          "sha256": "2f6a645ae5df1a039d61080096290ddaee321b154ac9d56d628c73f70f4e42e5",
          "sha1": "bbabf87a7824655e1070d96cb728c132bc3a10b7",
          "md5": "218137dbe54f84ccbb41a872577992b4"
        }
      ]
    }
  ]
}
