{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fabricators_of_create.Porting-Lib",
    "module": "gametest",
    "version": "3.1.0-beta+1.20.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "gametest-3.1.0-beta+1.20.4.jar",
          "url": "gametest-3.1.0-beta+1.20.4.jar",
          "size": 94201,
          "sha512": "c2eb013fe3f8a1d3d8e75af6f3e9d575e70e0beef70815d29050d2d0db88a6e580a80cd79a25786efc2bf9965a8a694965a94ca3ba932376a5e6258acb86fbc2",
          "sha256": "a840d96d7153266b94e261268e6a88c01ea2427790bddc45f675a238f0596945",
          "sha1": "4ef14d19271d931658f2e00f7423d2d462c652a6",
          "md5": "a958e5b445cd04eb871695f4185643bc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "gametest-3.1.0-beta+1.20.4.jar",
          "url": "gametest-3.1.0-beta+1.20.4.jar",
          "size": 94201,
          "sha512": "c2eb013fe3f8a1d3d8e75af6f3e9d575e70e0beef70815d29050d2d0db88a6e580a80cd79a25786efc2bf9965a8a694965a94ca3ba932376a5e6258acb86fbc2",
          "sha256": "a840d96d7153266b94e261268e6a88c01ea2427790bddc45f675a238f0596945",
          "sha1": "4ef14d19271d931658f2e00f7423d2d462c652a6",
          "md5": "a958e5b445cd04eb871695f4185643bc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "gametest-3.1.0-beta+1.20.4-sources.jar",
          "url": "gametest-3.1.0-beta+1.20.4-sources.jar",
          "size": 31384,
          "sha512": "b67b35a475768f3efccc9fb81be63e365aec476a42247cccc4507e0434bf849cd5b47d21144d96c90269c8890d1fb6ca8b87b15061421c599de0e3f03a3fe350",
          "sha256": "674f2ab0e0e5d6c971adb4710e2373f8404d39fc7b4b4011e2e7f51e5f3b2994",
          "sha1": "1d1f323cf9ba118d8e1a3c1461be09c4cd7796ab",
          "md5": "9576a8ff34bf80bdbcd0b314facf7eff"
        }
      ]
    }
  ]
}
