{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.fabricators_of_create.Porting-Lib",
    "module": "model_materials",
    "version": "3.1.0-beta+1.20.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.6"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "model_materials-3.1.0-beta+1.20.4.jar",
          "url": "model_materials-3.1.0-beta+1.20.4.jar",
          "size": 189211,
          "sha512": "ac8375a713920853604829b7bfaf1184f6322791b75cf5e3621c8d62a7de5ff2ede56ab8c171209b748a82d9d7a5835bec10dd8c7652b6ed9a0b33a6c64e453c",
          "sha256": "fc3cf5c816fa63a6bc7bbdf90a698f641aac3889901ca3d4345babaa3b34d82a",
          "sha1": "1f5674f2c3558073f4db145057b8ffaad63a02d1",
          "md5": "76fd45b722faa512ce7b427ce06409d1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "io.github.fabricators_of_create.Porting-Lib",
          "module": "core",
          "version": {
            "requires": "3.1.0-beta+1.20.4"
          }
        },
        {
          "group": "net.fabricmc",
          "module": "fabric-loader",
          "version": {
            "requires": "0.15.7"
          }
        },
        {
          "group": "net.fabricmc.fabric-api",
          "module": "fabric-api",
          "version": {
            "requires": "0.96.4+1.20.4"
          }
        }
      ],
      "files": [
        {
          "name": "model_materials-3.1.0-beta+1.20.4.jar",
          "url": "model_materials-3.1.0-beta+1.20.4.jar",
          "size": 189211,
          "sha512": "ac8375a713920853604829b7bfaf1184f6322791b75cf5e3621c8d62a7de5ff2ede56ab8c171209b748a82d9d7a5835bec10dd8c7652b6ed9a0b33a6c64e453c",
          "sha256": "fc3cf5c816fa63a6bc7bbdf90a698f641aac3889901ca3d4345babaa3b34d82a",
          "sha1": "1f5674f2c3558073f4db145057b8ffaad63a02d1",
          "md5": "76fd45b722faa512ce7b427ce06409d1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "model_materials-3.1.0-beta+1.20.4-sources.jar",
          "url": "model_materials-3.1.0-beta+1.20.4-sources.jar",
          "size": 5572,
          "sha512": "5933a0c5a0f79d3777433a21315a913c302b1bf9dfbd0e791cd0230d03667e4cdb6732a7bd83ec7fc52eaf3fa97788f9f89731dda2859cc6a62e24433560b47b",
          "sha256": "f3821c7a71bc2d39686e0dbc02b249ceb3e5da386cdd26030c8b9fd9e0d8e867",
          "sha1": "8ec734d2d849e13e6cd417060686ba80ac444306",
          "md5": "94a33d5ff0ac0d5d747e3aa0882f59c1"
        }
      ]
    }
  ]
}
